---
apiVersion: v1
kind: Namespace
metadata:
  name: hadoop
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hadoop-master
  namespace: hadoop
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
   name: secrets-configmaps-get-put
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "update", "create"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "update", "create"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hadoop-master-role-binding
subjects:
- kind: ServiceAccount
  name: hadoop-master
  namespace: hadoop
roleRef:
  kind: ClusterRole
  name: secrets-configmaps-get-put
  apiGroup: rbac.authorization.k8s.io
---
kind: Service
apiVersion: v1
metadata:
  name: hadoop-master
  namespace: hadoop
  labels:
    name: hadoop-master-services
spec:
  selector:
    name: hadoop-master
  ports:
  - name: port-0
    port: 8030
  - name: port-1
    port: 8031
  - name: port-2
    port: 8032
  - name: port-3
    port: 8033
  - name: port-4
    port: 8040
  - name: port-5
    port: 8042
  - name: port-6
    port: 8088
  - name: port-7
    port: 9000
  - name: port-8
    port: 9864
  - name: port-9
    port: 9866
  - name: port-10
    port: 9867
  - name: port-11
    port: 9868
  - name: port-12
    port: 9870
  - name: port-13
    port: 10020
  - name: port-14
    port: 10033
  - name: port-15
    port: 13562
  - name: port-16
    port: 19888
  - name: port-17
    port: 33011
  - name: port-18
    port: 37319
  - name: port-19
    port: 40469
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hadoop-role
  namespace: hadoop
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "update", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hadoop-role-binding
  namespace: hadoop
subjects:
- kind: ServiceAccount
  name: hadoop-master
  namespace: hadoop
roleRef:
  kind: Role
  name: hadoop-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hadoop-master
  namespace: hadoop
  labels:
    name: hadoop-master
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      name: hadoop-master
  replicas: 1
  template:
    metadata:
      labels:
        name: hadoop-master
    spec:
      serviceAccountName: hadoop-master
      containers:
      - name: hadoop-master
        image: eiswar/hadoop:latest
        command: ["/usr/local/hadoop/sbin/bootstrap.sh"]
        args: ["master"]
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /hdfs
          name: hdfs-namenode-data
      volumes:
      - name: hdfs-namenode-data
        hostPath:
          path: /hadoop
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hadoop-worker
  namespace: hadoop
spec:
  selector:
    matchLabels:
      name: hadoop-worker
  template:
    metadata:
      labels:
        name: hadoop-worker
    spec:
      hostNetwork: true
      serviceAccountName: hadoop-master
      containers:
      - name: hadoop-worker
        image: eiswar/hadoop:latest
        command: ["/usr/local/hadoop/sbin/bootstrap.sh"]
        args: ["worker"]
        volumeMounts:
        - mountPath: /hdfs
          name: hdfs-data
      volumes:
      - name: hdfs-data
        hostPath:
          path: /hdfs
